# Generated by Django 3.0.5 on 2020-04-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='path',
        ),
    ]
